development:
  adapter: sqlite3
  database: /var/lib/zdashboard/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: /var/lib/zdashboard/development.sqlite3
  pool: 5
  timeout: 5000
