development:
  host: localhost
  base: dc=zarafa,dc=com
  bind_dn: cn=admin,dc=zarafa,dc=com
  password: secretpassword

development:
  host: localhost
  base: dc=zarafa,dc=com
  bind_dn: cn=admin,dc=zarafa,dc=com
  password: secretpassword

development:
  host: localhost
  method: :tls
  base: dc=zarafa,dc=com
  bind_dn: cn=admin,dc=zarafa,dc=com
  password: secretpassword

bases:
  development:
    users: ou=users
    groups: ou=groups
